# Generated by Django 5.0.3 on 2024-04-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='photo products'),
            preserve_default=False,
        ),
    ]
