# Generated by Django 5.0.3 on 2024-04-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimage_product_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='product quantity'),
        ),
    ]
