# Generated by Django 5.0.3 on 2024-04-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descriptions',
            field=models.TextField(default=1, verbose_name='product description'),
            preserve_default=False,
        ),
    ]
