# Generated by Django 5.0.3 on 2024-04-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='product quantity'),
        ),
    ]
