# Generated by Django 5.0.3 on 2024-04-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/', verbose_name='product card image')),
                ('title', models.CharField(max_length=255, verbose_name='title for card')),
                ('description', models.TextField(verbose_name='description for card')),
            ],
            options={
                'verbose_name': 'Product card',
            },
        ),
    ]
