# Generated by Django 5.0.3 on 2024-04-11 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcard',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_cards', to='products.product'),
            preserve_default=False,
        ),
    ]
