# Generated by Django 5.0.3 on 2024-04-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productcard_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Настройки продукта'},
        ),
        migrations.AlterModelOptions(
            name='productcard',
            options={'verbose_name': 'Карточка продукта'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображение продукта'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=1, verbose_name='описание продукта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(blank=True, default=1, verbose_name='количество продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0, verbose_name='цена продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, verbose_name='название продукта'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='description',
            field=models.TextField(verbose_name='Описание карточки продукта'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Изображение карточки продукта'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок карточки продукта'),
        ),
        migrations.AlterUniqueTogether(
            name='productcard',
            unique_together={('title', 'description')},
        ),
    ]
