# Generated by Django 5.0.3 on 2024-04-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_options_alter_productcard_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product settings'},
        ),
        migrations.AlterModelOptions(
            name='productcard',
            options={'verbose_name': 'Product Card'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Products image'},
        ),
        migrations.AlterUniqueTogether(
            name='productcard',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='descriptions',
            field=models.TextField(default=1, verbose_name='product description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='product quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0, verbose_name='product price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, verbose_name='products name'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='description',
            field=models.TextField(verbose_name='Description for Card'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Product Card Image'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title for Card'),
        ),
        migrations.AlterUniqueTogether(
            name='productcard',
            unique_together={('image', 'title', 'description')},
        ),
    ]
