# Generated by Django 5.0.3 on 2024-04-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Banner Header')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Banner photo')),
                ('logo', models.ImageField(upload_to='image/', verbose_name='Site logo')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, max_length=255, null=True, verbose_name='linkedin')),
            ],
            options={
                'verbose_name': 'Site settings',
            },
        ),
    ]
