# Generated by Django 5.0.3 on 2024-04-02 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='title',
        ),
    ]
