# Generated by Django 5.0.3 on 2024-04-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_questions_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answers',
            field=models.TextField(verbose_name='answers'),
        ),
    ]
