# Generated by Django 5.0.3 on 2024-04-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_questions_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сonfigurations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/', verbose_name='photo (configurations)')),
                ('title', models.CharField(max_length=255, verbose_name='title (configurations)')),
                ('descriptions', models.TextField(verbose_name='descriptions (configurations)')),
            ],
            options={
                'verbose_name': 'Configurations (products)',
            },
        ),
    ]
