# Generated by Django 5.0.3 on 2024-04-02 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_сonfigurations'),
    ]

    operations = [
        migrations.CreateModel(
            name='СonfigurationsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/', verbose_name='photo (configurations)')),
            ],
            options={
                'verbose_name': 'Configurations (products) image',
            },
        ),
        migrations.AlterField(
            model_name='сonfigurations',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations_image', to='base.сonfigurationsimage'),
        ),
    ]
